### ISSUE TITLE
本地集成出错

### ISSUE THREAD

**Issue by mengluohuashi** [zhontai/Admin.IdentityServer#1]
![image](https://user-images.githubusercontent.com/21031397/101452670-01d4ba80-3969-11eb-8698-2ad4fad33d9b.png)
本地。Admin.UI集成，出错，Admin.Ui需要改哪些配置呢

**Comment by TTonlyV5** [comment]
一般都是配置url有问题

**Comment by zhontai** [comment]
已修复，拉取最新版本
